experiment:
  name: lunar_lander_a2c
  run_root: runs

seed: 123

env:
  id: LunarLander-v3
  num_envs: 8

model:
  name: discrete_mlp
  kwargs:
    hidden_sizes: [256, 256]

train:
  steps: 120000
  learning_rate: 0.0005
  value_loss_coef: 0.5
  discount_factor: 0.99
  rollout_steps: 40
  max_grad_norm: 0.5

eval:
  every_steps: 5000
  episodes: 10
  seed: 10000

logging:
  loss_every_steps: 1000
  save_plot: true
