experiment:
  name: mountain_car_a2c
  run_root: runs

seed: 456

env:
  id: MountainCar-v0
  num_envs: 8

model:
  name: discrete_mlp
  kwargs:
    hidden_sizes: [256]

train:
  steps: 500000
  learning_rate: 0.0003
  value_loss_coef: 0.5
  discount_factor: 0.999
  rollout_steps: 100
  max_grad_norm: null

eval:
  every_steps: 10000
  episodes: 5
  seed: 10000

logging:
  loss_every_steps: 1000
  save_plot: true
