experiment:
  name: mountain_car_continuous_ppo
  run_root: runs

seed: 123

env:
  id: MountainCarContinuous-v0
  num_envs: 1

model:
  name: continuous_mlp
  kwargs:
    hidden_sizes: [64, 64]
    activation: relu
    layer_norm: true
    orthogonal_init: false
    init_log_std: -3.29
    log_std_min: -20.0
    log_std_max: 2.0

train:
  steps: 20000
  learning_rate: 0.0000777
  discount_factor: 0.9999
  gae_lambda: 0.9
  rollout_steps: 8
  minibatch_size: 8
  epochs: 10
  clip_coef: 0.1
  value_coef: 0.19
  entropy_coef: 0.00429
  max_grad_norm: 5.0

eval:
  every_steps: 2000
  episodes: 10
  seed: 10000

logging:
  loss_every_steps: 1000
  save_plot: true
