experiment:
  name: pendulum_a2c
  run_root: runs

seed: 123

env:
  id: Pendulum-v1
  num_envs: 8

model:
  name: continuous_mlp
  kwargs:
    hidden_sizes: [64, 64]
    layer_norm: true
    init_log_std: -2.0
    log_std_min: -20.0
    log_std_max: 2.0

train:
  steps: 1000000
  learning_rate: 0.0007
  value_loss_coef: 0.4
  discount_factor: 0.9
  rollout_steps: 8
  max_grad_norm: 0.5

eval:
  every_steps: 20000
  episodes: 10
  seed: 10000

logging:
  loss_every_steps: 1000
